spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  r2dbc:
    url: 'r2dbcs:mysql://122.9.35.239:3306/zgj?createDataBaseIfNotExist=true&serverTimezone=Asia/Shanghai'
    username: root
    password: 532129
    pool:
      enabled: true
      initial-size: 1
      validation-query: select 1
    servlet:
      multipart:
        max-file-size: -1 #???????
        max-request-size: -1 #????
    jackson:
      default-property-inclusion: non_null #?????????
logging:
  level:
    root: info
    com:
      example: debug
    org:
      springframework:
        r2dbc: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
my:
  secretKey: '2024yea01month'
  upload: 'E:/ProjectFile'
